const quotes = [
    "Believe in yourself.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Push yourself, because no one else is going to do it for you.",
    "Success is what happens after you have survived all your mistakes.",
    "Work hard in silence. Let success make the noise.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Stay positive, work hard, make it happen.",
    "Failure is the opportunity to begin again more intelligently.",
    "Don’t watch the clock; do what it does. Keep going.",
    "If you can dream it, you can do it.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Don’t wish for it. Work for it.",
    "Go the extra mile, it’s never crowded.",
    "Your only limit is your mind.",
    "Doubt kills more dreams than failure ever will.",
    "Don’t be afraid to give up the good to go for the great.",
    "You are stronger than you think.",
    "Start where you are. Use what you have. Do what you can.",
    "You miss 100% of the shots you don’t take.",
    "The best time to plant a tree was 20 years ago. The second-best time is now.",
    "It always seems impossible until it’s done.",
    "Quality is not an act, it is a habit.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t let yesterday take up too much of today.",
    "The future depends on what you do today.",
    "Difficult roads often lead to beautiful destinations.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "Opportunities don’t happen. You create them.",
    "Don’t limit your challenges, challenge your limits.",
    "The only place where success comes before work is in the dictionary.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The harder you fall, the higher you bounce.",
    "It does not matter how slowly you go as long as you do not stop.",
    "If you're going through hell, keep going.",
    "Perseverance is not a long race; it's many short races one after the other.",
    "Champions keep playing until they get it right.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Small progress is still progress.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "The best view comes after the hardest climb.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Don’t raise your voice, improve your argument.",
    "Discipline is doing what needs to be done, even if you don’t want to do it.",
    "Motivation gets you going, but discipline keeps you growing.",
    "Don’t tell people your plans. Show them your results.",
    "The expert in anything was once a beginner.",
    "Doubt whom you will, but never yourself.",
    "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
    "Make each day your masterpiece.",
    "Strive not to be a success, but rather to be of value.",
    "A river cuts through rock not because of its power, but because of its persistence.",
    "You don’t need to see the whole staircase, just take the first step.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "Success isn’t always about greatness. It’s about consistency.",
    "Stay hungry, stay foolish.",
    "Set your goals high, and don’t stop till you get there.",
    "Never dream about success. Work for it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Courage is one step ahead of fear.",
    "Turn your wounds into wisdom.",
    "What we think, we become.",
    "When you feel like stopping, think about why you started.",
    "If you get tired, learn to rest, not quit.",
    "Stay away from those people who try to disparage your ambitions.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Work until your idols become your rivals.",
    "Fall seven times, stand up eight.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "Don’t call it a dream, call it a plan.",
    "Dare to dream, dare to try, dare to fail, dare to succeed.",
    "The distance between dreams and reality is called action.",
    "Be so good they can’t ignore you.",
    "Consistency is more important than perfection.",
    "Discomfort is the currency of success.",
    "The secret of getting ahead is getting started.",
    "Stop doubting yourself, work hard, and make it happen.",
    "Someday is not a day of the week.",
    "Act as if what you do makes a difference. It does.",
    "The way to get started is to quit talking and begin doing."
  ];
  
  function newQuote() {
    const quote = quotes[Math.floor(Math.random() * quotes.length)];
    document.getElementById('quote').textContent = quote;
  }
  
  // Load first quote immediately
  newQuote();
  